 ALTER TABLE verification_tokens
      ALTER COLUMN expires_at TYPE TIMESTAMP WITH TIME ZONE,
      ALTER COLUMN used_at TYPE TIMESTAMP WITH TIME ZONE,
      ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;